const questions = [
  {
    id: 1,
    question: "En dónde fue la primera cita de {both}?",
    answers: ["Trece Lunas", "Sierra Madre Brewing Co.", "En un antro"],
  },
  {
    id: 2,
    question: "Cuántos años tiene {she}?",
    answers: ["32", "28", "31"],
  },
  {
    id: 3,
    question: "Cuántos años tiene {he}?",
    answers: ["33", "31", "30"],
  },
  { id: 4, question: "", answers: ["", "", ""] },
  { id: 5, question: "", answers: ["", "", ""] },
  { id: 6, question: "", answers: ["", "", ""] },
  { id: 7, question: "", answers: ["", "", ""] },
  { id: 8, question: "", answers: ["", "", ""] },
  { id: 9, question: "", answers: ["", "", ""] },
  { id: 10, question: "", answers: ["", "", ""] },
  { id: 11, question: "", answers: ["", "", ""] },
  { id: 12, question: "", answers: ["", "", ""] },
  { id: 13, question: "", answers: ["", "", ""] },
  { id: 14, question: "", answers: ["", "", ""] },
  { id: 15, question: "", answers: ["", "", ""] },
  { id: 16, question: "", answers: ["", "", ""] },
  { id: 17, question: "", answers: ["", "", ""] },
  { id: 18, question: "", answers: ["", "", ""] },
  { id: 19, question: "", answers: ["", "", ""] },
  { id: 20, question: "", answers: ["", "", ""] },
  { id: 21, question: "", answers: ["", "", ""] },
  { id: 22, question: "", answers: ["", "", ""] },
  { id: 23, question: "", answers: ["", "", ""] },
  { id: 24, question: "", answers: ["", "", ""] },
  { id: 25, question: "", answers: ["", "", ""] },
  { id: 26, question: "", answers: ["", "", ""] },
  { id: 27, question: "", answers: ["", "", ""] },
  { id: 28, question: "", answers: ["", "", ""] },
  { id: 29, question: "", answers: ["", "", ""] },
  { id: 30, question: "", answers: ["", "", ""] },
  { id: 31, question: "", answers: ["", "", ""] },
  { id: 32, question: "", answers: ["", "", ""] },
  { id: 33, question: "", answers: ["", "", ""] },
  { id: 34, question: "", answers: ["", "", ""] },
  { id: 35, question: "", answers: ["", "", ""] },
  { id: 36, question: "", answers: ["", "", ""] },
  { id: 37, question: "", answers: ["", "", ""] },
  { id: 38, question: "", answers: ["", "", ""] },
  { id: 39, question: "", answers: ["", "", ""] },
  { id: 40, question: "", answers: ["", "", ""] },
  { id: 41, question: "", answers: ["", "", ""] },
  { id: 42, question: "", answers: ["", "", ""] },
  { id: 43, question: "", answers: ["", "", ""] },
  { id: 44, question: "", answers: ["", "", ""] },
  { id: 45, question: "", answers: ["", "", ""] },
  { id: 46, question: "", answers: ["", "", ""] },
  { id: 47, question: "", answers: ["", "", ""] },
  { id: 48, question: "", answers: ["", "", ""] },
  { id: 49, question: "", answers: ["", "", ""] },
  { id: 50, question: "", answers: ["", "", ""] },
  { id: 51, question: "", answers: ["", "", ""] },
  { id: 52, question: "", answers: ["", "", ""] },
  { id: 53, question: "", answers: ["", "", ""] },
  { id: 54, question: "", answers: ["", "", ""] },
  { id: 55, question: "", answers: ["", "", ""] },
  { id: 56, question: "", answers: ["", "", ""] },
  { id: 57, question: "", answers: ["", "", ""] },
  { id: 58, question: "", answers: ["", "", ""] },
  { id: 59, question: "", answers: ["", "", ""] },
  { id: 60, question: "", answers: ["", "", ""] },
  { id: 61, question: "", answers: ["", "", ""] },
  { id: 62, question: "", answers: ["", "", ""] },
  { id: 63, question: "", answers: ["", "", ""] },
  { id: 64, question: "", answers: ["", "", ""] },
  { id: 65, question: "", answers: ["", "", ""] },
  { id: 66, question: "", answers: ["", "", ""] },
  { id: 67, question: "", answers: ["", "", ""] },
  { id: 68, question: "", answers: ["", "", ""] },
  { id: 69, question: "", answers: ["", "", ""] },
  { id: 70, question: "", answers: ["", "", ""] },
  { id: 71, question: "", answers: ["", "", ""] },
  { id: 72, question: "", answers: ["", "", ""] },
  { id: 73, question: "", answers: ["", "", ""] },
  { id: 74, question: "", answers: ["", "", ""] },
  { id: 75, question: "", answers: ["", "", ""] },
  { id: 76, question: "", answers: ["", "", ""] },
  { id: 77, question: "", answers: ["", "", ""] },
  { id: 78, question: "", answers: ["", "", ""] },
  { id: 79, question: "", answers: ["", "", ""] },
  { id: 80, question: "", answers: ["", "", ""] },
  { id: 81, question: "", answers: ["", "", ""] },
  { id: 82, question: "", answers: ["", "", ""] },
  { id: 83, question: "", answers: ["", "", ""] },
  { id: 84, question: "", answers: ["", "", ""] },
  { id: 85, question: "", answers: ["", "", ""] },
  { id: 86, question: "", answers: ["", "", ""] },
  { id: 87, question: "", answers: ["", "", ""] },
  { id: 88, question: "", answers: ["", "", ""] },
  { id: 89, question: "", answers: ["", "", ""] },
  { id: 90, question: "", answers: ["", "", ""] },
  { id: 91, question: "", answers: ["", "", ""] },
  { id: 92, question: "", answers: ["", "", ""] },
  { id: 93, question: "", answers: ["", "", ""] },
  { id: 94, question: "", answers: ["", "", ""] },
  { id: 95, question: "", answers: ["", "", ""] },
  { id: 96, question: "", answers: ["", "", ""] },
  { id: 97, question: "", answers: ["", "", ""] },
  { id: 98, question: "", answers: ["", "", ""] },
  { id: 99, question: "", answers: ["", "", ""] },
];

export default questions;
